### ISSUE TITLE
Add kramdown and jekyll-feed by default

### ISSUE THREAD

**Issue by bexelbie** [jekyll/docker#78] opened 2016-01-06 16:45 UTC
Per http://jekyllrb.com/docs/configuration/ it is the default markdown interpreter.

Kramdown and jekyll-feed are listed in the README, but required a separate install in my Gemfile.  I had to create a Gemfile to install jekyll-paginate.  Does the use of a Gemfile override all built-ins?

**Comment by envygeeks** [comment] 2016-01-07 12:30
Your Gemfile will not affect our gems unless it uses Git once you use Git we can no longer use shared-gems or `gem install` to install your Gemfile, we must use `vendor/bundle` which will disable your access to our default gems... I have not tired to work around that.  Otherwise it should be installed via Gem.  That said, all our images provide Kramdown and Jekyll-Feed by default.

What is in your Gemfile?

**Comment by bexelbie** [comment] 2016-01-07 13:47
@envygeeks 

```
source 'https://rubygems.org'

group :jekyll_plugins do
# These are from the _config.yml
  gem "jekyll-paginate"
  # These are supposed to be built-in
  gem "jekyll-feed"
  gem "kramdown"
  # This needed for my use case
  gem "jekyll-watch"
end
```

**Comment by envygeeks** [comment] 2016-01-07 13:48
@bexelbie I seen it after i posted that... in the other thread, this is actually an upstream bug.

**Comment by bexelbie** [comment] 2016-01-07 13:49
upstream as in envygeeks/alpine ?

**Comment by envygeeks** [comment] 2016-01-07 13:51
`envygeeks/alpine` actually sits in `envygeeks/docker`, there is no need for you to file a Ticket there as I can close this ticket from that repo since I'm an author on both.

/cc @jhabdas so he gets notification when this issue is resolved.

**Comment by envygeeks** [comment] 2016-01-07 13:52
Here is a link to the repo just in-case you wanted to know: https://github.com/envygeeks/docker, it provides a set of helpers we use on this image: https://github.com/envygeeks/docker/blob/master/copy/usr/local/share/docker/helpers.d/ruby#L221 that helper forgot to enable shared, global and system gems.

**Comment by envygeeks** [comment] 2016-01-07 14:27
Okay, I take that back, after further research this is caused by: https://github.com/jekyll/docker/issues/53, because somebody wanted to be able to do lazy Git, so it wasn't originally an upstream problem, but now it is.  Upstream will have to get smarter about bundler.

**Comment by envygeeks** [comment] 2016-01-07 14:29
Actually, I'm gonna think on it for a few minutes and decide if I want to revert to my initial better judgement against #53 or come up with another solution to make this image easy for users again.

**Closed** 2016-01-08 20:14 UTC
Labels: bug, upstream:envygeeks/docker, ★★★★
