### ISSUE TITLE
Docker-compose example on README doesn't work

### ISSUE THREAD

**Issue by aom** [jekyll/docker#188] opened 2017-10-13 08:34 UTC
I took the example `docker-compose.yml` from `README.md` and only added version number to top (tried with 2.1 as well). I also tried `:latest` tag.

```
➜  cat docker-compose.yml
version: '3'

services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:3.5
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
➜  docker-compose run site jekyll new site
su-exec: new: No such file or directory
```

I am unfamiliar with [su-exec](https://github.com/ncopa/su-exec) which seems to be causing issues here.

I'm using Docker for Mac:

Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c

**Comment by aom** [comment] 2017-10-13 08:41
Removing bundler volume fixes the issue. Ofc you'll loose caching ability then.

**Comment by envygeeks** [comment] 2017-10-13 08:59
You only lose caching long enough to generate your Gemfile via Jekyll.  This is expected behavior really, and I deemed it unnecessary to complicate life by adding a secondary service just to run `new` since it's something only done once.  If it's a problem I think I would rather remove the `new` example rather than add an extra one-time service, or to remove the caching example entirely as you don't even need caching if you are running `jekyll new` because we provide every dependency Jekyll would want, and some on-top of that to reduce the need for caching.

**Comment by envygeeks** [comment] 2017-10-13 09:02
I'm open to suggestions as well if you have any.

**Comment by envygeeks** [comment] 2017-10-14 01:20
Closing in favor of #189.

**Closed by envygeeks** 2017-10-14 01:20 UTC
Labels: discussion, documentation, pending-feedback
