### ISSUE TITLE
Regeneration is slow with docker-machine --force_polling

### ISSUE THREAD

**Issue by greathouse** [jekyll/docker#68] opened 2015-12-08 15:08 UTC
I am trying to run jekyll on OSX with docker-machine. Jekyll works and serves the pages just fine. However, when making changes, the regeneration process takes upwards of 3+ minutes.

Steps:
1. Start Jekyll
```docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p $(docker-machine ip `docker-machine active`):4000:4000 jekyll/jekyll jekyll s --force_polling```
2. Make change to file
3. Jekyll log shows "Regenerating: 1 file(s) changed at 2015-12-08 14:59:41" immediately after saving the file.
4. Then wait...
5. ...done in 190.791034435 seconds.

Any ideas or things to try? Any more information needed to assist?

**Comment by envygeeks** [comment] 2015-12-08 15:11
@greathouse can you provide a repository? And also can you provide me with the output of:

```sh
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -e DEBUG=true \
  -p $(docker-machine ip `docker-machine active`):4000:4000 \
    jekyll/jekyll jekyll s --force_polling
``

You might need to update your image as that was recently pushed within the last few days and not everybody updates as quickly as our build servers do (instantly.) So make sure to update your image before you run that command!

**Comment by envygeeks** [comment] 2015-12-08 15:12
OH: Dully note, the DEBUG trigger will give you some hardcore output as it will Debug *everything* from our boot process to our installation process to bundlers installation process to all of Jekyll's stuff too.  So prepare to be bombarded with debug information.

**Comment by greathouse** [comment] 2015-12-08 15:34
It appears to be spending a lot of time in the "EntryFilter". Sample: `EntryFilter: excluded?(/wp-content/uploads/2012/03/Dell.SystemInfo-300x127.png) ==> false`

I converted a Wordpress site so there are a lot of various sized images that Wordpress made. I can try removing the ones I don't use to see if it helps. I wouldn't say I have an over abundance of images. It was a small blog site that was converted.

**Comment by envygeeks** [comment] 2015-12-08 15:42
@greathouse `jekyll-assets` might be able to help you manage those more intelligently if they are used in posts and pages with the {% img %} tag since it processes outside of Jekyll and uses Sprockets and caches and is explicit in what it includes (unless you make it implicit) it shouldn't do all that constantly on every build, and because it works with Jekyll's caching it won't do it every time.

**Comment by envygeeks** [comment] 2015-12-08 16:32
Gonna go ahead and close this since it's an upstream problem and nothing we can realistically do about it, your option are to reduce your assets, switch to `jekyll-assets`, or exclude the folder entirely and manually add the assets.  If you wish you can file a ticket on https://github.com/jekyll/jekyll/issues/new and spark a conversation about it, but we cannot fix it here.

**Closed by envygeeks** 2015-12-08 16:32 UTC
Labels: invalid, question

**Comment by jpowie01** [comment] 2017-05-05 20:59
Hi all,
I've got the same issue as above on my macOS. But I've found this issue with simple (and empty) project - nearly "Hello, World". It seems that regeneration breaks when path to the project contains non-ASCII characters.

Examples: 
```
/Users/jakubpowierza/Desktop/test/My Page - FAST
/Users/jakubpowierza/Desktop/ąśćź/My Page - REALLY SLOW
```

Main issues were connected with these steps (when I run jekyll with --debug):
```
my_page    |          Rendering: css/main.scss
my_page    |   Pre-Render Hooks: css/main.scss
my_page    |   Rendering Liquid: css/main.scss
my_page    |   Rendering Markup: css/main.scss
```

I think that there might be an issue with some plugins or Jekyll itself. I can't post my repository but all I use is stored in my Gemfile:
```
source 'https://rubygems.org'
gem 'json'
gem 'listen'
gem 'jekyll'
gem 'jekyll-watch'
gem 'jekyll-archives'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
```

I run my Docker using docker-compose with below configuration:
```yaml
my_page:
    image: jekyll/jekyll:pages
    container_name: my_page
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
```

Timings:
- ASCII path:
    - first build: 4.429 seconds
    - rebuild: 3.128 seconds
- non-ASCII path:
    - first build: 4.238 seconds
    - rebuild: 119.936 seconds!!!

I hope that will help somebody. I've found this after 3 hours of debugging :) If you need something for debugging - contact me. If I should post this bug somewhere else - tell me and I'll do this ASAP.

Thanks,
Jakub Powierza

**Comment by envygeeks** [comment] 2017-05-05 21:12
Hi, this would either be a problem with Jekyll or with Docker itself.  We control neither.

**Comment by jpowie01** [comment] 2017-05-05 21:13
Thanks, I'll post it in the main Jekyll repo.

**Comment by jdthorpe** [comment] 2017-07-01 16:01
I'm having what is probably the same issue.  Here are the details:   I'm using `Docker version 17.03.1-ce, build c6d412e` on OSX 10.12.4 (Sierra).   I created a file called `helloworld.md` in the current directory with the following:

```markdown
---
title: Hello World
---
# test
```

and then ran:

```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 4000:4000  jekyll/jekyll jekyll serve --force_polling
```

which printed the following lines at the console:

```
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.316 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
    Server address: http://0.0.0.0:4000
  Server running... press ctrl-c to stop.
```


Then opening `localhost:4000` dutifully opened a page containing

<hr>
<h1>test</h1>
<hr>

When I updated `helloworld.md` to:

```markdown
---
title: Hello World
---
# test
test
```

The following line is printed to the console:

```
      Regenerating: 1 file(s) changed at 2017-06-28 02:59:08
```

but reloading the page does not cause the page to be updated.   If I stop the container and restart it, and reload the page I get the page I expected:

<hr>
<h1>test</h1>
test
<hr>

Wondering if this is an EBCAK or if Jekyll is not running correctly in the container.

**Comment by envygeeks** [comment] 2017-07-01 17:05
This probably doesn't originate from Jekyll or Jekyll's Docker image, it more than likely originates from Oracles software (VirtualBox -- it has known bugs involving what you stated on OS X) or in Docker itself (unlikely, but I don't remember if Docker Machine and Native Docker are still using components of VirtualBox in some places.)

**Comment by envygeeks** [comment] 2017-07-01 17:06
I will concede though, it could be the listen gem, and not directly, but because of Jekyll.  AFAIW and AFAIR it's still locked to an old version for Jekyll-Watch because of reasons I can't remember since it's been so long.  I don't know if that could be a root cause or not.

**Comment by jdthorpe** [comment] 2017-07-01 22:16
FWIW, installed Docker on my Windows machine with same results -- so not an OSX specific bug...

**Comment by envygeeks** [comment] 2017-07-01 22:35
Even though I tailored that message for OS X those Oracle bugs affect everything but native Linux (because we need no translation.)

**Comment by tivvit** [comment] 2017-07-06 18:02
It happened to me on Linux too. But only when using collections.

**Comment by envygeeks** [comment] 2017-07-06 18:04
Everything inside of 3.2 plus is a collection. That needs more elaboration on the Jekyll tracker. This is not a big in our image directly.

**Comment by tivvit** [comment] 2017-07-06 18:06
thanks for the answer, I will post it there. I just figured out that the problem is that the collections contained markdown.
