### ISSUE TITLE
.html extension is not required on GitHub Pages

### ISSUE THREAD

**Issue by niekbosch** [jekyll/docker#28] opened 2015-09-08 06:15 UTC
When viewing my documentation on GitHub Pages, I do not need to add the .html extension to filenames. However, using this Docker image, this is required. This breaks all my links, because they are in the form of:
```
[link to other page](other-page-without-extension)
```
GitHub Pages does work when adding the extension, so I could also change my code. However, if you're trying to be as close to GH Pages as possible, this is an issue.

**Comment by envygeeks** [comment] 2015-09-08 09:34
Please elaborate this more, or provide a repo with the source and steps to reproduce it on that source.

**Comment by niekbosch** [comment] 2015-09-08 14:39
Yes of course, sorry for the too short original message:

The GitHub Pages for my repo (https://github.com/sara-nl/clouddocs) can be found here: http://sara-nl.github.io/clouddocs/

In the index page (for example), I have several links to other pages. In those links I do not specify the .html extension (and certainly not the .markdown extension), yet they work fine in GitHub Pages.

When I run the Jekyll image on Docker on my own laptop, following the links result in a 404 Not Found response. Yet, when I then add the '.html' extension in the address bar of my browser, he does find the file.

Steps to reproduce, in bash (or comparable shell):
```bash
git clone https://github.com/sara-nl/clouddocs.git
cd clouddocs
sudo docker run --detach --name=jekyll --label=jekyll --volume=$(pwd):/srv/jekyll -t jekyll/jekyll jekyll s
sudo docker inspect jekyll | grep '"IPAddress"' | sed -re 's|[[:space:]]*"IPAddress": "([^"]+)",|View your documentation at http://\1:4000|'
```

This last command outputs the URL to the documentation in the container (i.e. an HTTP URL on port 4000 of the container). Then:

1. Copy-paste the URL to your browser
1. Click a link to a next page, e.g. 'Replacing the VirDir'
1. Observe the 404 response
1. Add '.html' to the address in the address bar and press enter
1. Observe the correct page
1. Go to http://sara-nl.github.io/clouddocs/ to view the GitHub Pages behaviour
1. Click on the same link (on the GitHub Pages domain), e.g. 'Replacing the VirDir'
1. Observe that the address does not contain the '.html' extension, but serves the correct page anyway.

**Comment by envygeeks** [comment] 2015-09-08 15:15
Thanks @niekbosch... this is actually a Jekyll problem but because we are explicitly supporting an old version of Jekyll... @parkr can you tell me if Jekyll 2.4 required the .html extension?

If it did then I'll happily work around it by building a custom version of the Jekyll command (or something else) that knocks out your serve and switches it to watch and starts Nginx for you this was something that was planned anyways for the super image but I'll split that up to get this fixed.

**Comment by parkr** [comment] 2015-09-08 15:18
> @parkr can you tell me if Jekyll 2.4 required the .html extension?

https://github.com/jekyll/jekyll/pull/3452 is slated to be released with Jekyll 3.

**Comment by envygeeks** [comment] 2015-09-08 15:19
Looks like I need to do it for both stable and pages, fair enough, thanks!

**Comment by parkr** [comment] 2015-09-08 15:20
@envygeeks Maybe just for `pages`, as that's the one we want to mimic GitHub Pages?

**Comment by envygeeks** [comment] 2015-09-08 15:21
@parkr that's fair point.  Yeah that makes it easier.

**Comment by niekbosch** [comment] 2015-09-08 15:32
Aha, I misread that remark about the ```pages``` label (thought all versions were trying to mimic GitHub Pages). Changed my documentation so that in the future I will use the ```pages``` images.

And thanks in advanced for fixing the problem!

**Comment by envygeeks** [comment] 2015-09-08 15:36
Yup, the only one that specifically tries to mimic github pages is the pages tag, it even uses their dependencies https://github.com/jekyll/docker-jekyll/blob/master/vendor/sync/pages (a part from me adding jekyll-compose because it's useful for everyone tbh) the only difference we can't control is the Ruby version and that's because it would diverge too much to compile an older Ruby plus they use 2.1 so it's not a big deal anyways.

**Closed** 2015-09-10 18:00 UTC
Labels: bug
